name: Build WDF Comparator EXE

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    tags: [ 'v*' ]
    paths:
      - "wdf_comparator.py"
      - "requirements.txt"
      - ".github/workflows/wdf.yml"

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~\AppData\Local\pip\Cache
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller

      - name: Build EXE with PyInstaller
        run: pyinstaller --onefile --windowed --name WDFComparator wdf_comparator.py

      - name: Upload artifact (EXE)
        uses: actions/upload-artifact@v4
        with:
          name: WDFComparator-windows
          path: dist/WDFComparator.exe
          if-no-files-found: error
